# A Docker compose file. It spins up the Django 
# server and creates the PostgreSQL database. 
services:
  frontend:
    build:
      context: ./frontend
    container_name: wealthwise-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    # Terminal for printing to console
    tty: true
  db:
    image: postgres:16
    container_name: wealthwise
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: wealthwise-django
    # 'command' runs the commands on build. It runs
    # Django's migrations and starts dev server.
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
