# A Docker compose file. It spins up the Django 
# server and creates the PostgreSQL database. 
services:
  db:
    image: postgres:16
    container_name: wealthwise
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: wealthwise-django
    volumes:
      - .:/Personal-Finance-Track-SWE-Group-6
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
