# Generated by Django 5.1.7 on 2025-04-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_amount',
        ),
    ]
