# Generated by Django 5.1.7 on 2025-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_deleted_at_transaction_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
