# Generated by Django 5.1.7 on 2025-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_budgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
