# Generated by Django 5.1.7 on 2025-05-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bill_website_url'),
        ('accounts', '0006_alter_budgets_amount'),
    ]

    operations = [
    ]
