name: Deploy Django App to Azure Web App (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: wealthwise.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="wealthwise.azurecr.io/wealthwise" 
          IMAGE_TAG="${{ github.sha }}" 
          FULL_IMAGE_NAME="${IMAGE_NAME}:${IMAGE_TAG}"

          echo "Building Docker image: $FULL_IMAGE_NAME"
          docker build -t $FULL_IMAGE_NAME .

          echo "Pushing Docker image: $FULL_IMAGE_NAME to ACR"
          docker push $FULL_IMAGE_NAME

          # Set the image name as an environment variable for the next step
          echo "DOCKER_IMAGE_NAME=${FULL_IMAGE_NAME}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          app-name: wealthwise
          images: ${{ env.DOCKER_IMAGE_NAME }}
